"""Tiny end-to-end runs of the real entry points, each as `python -m msdelta.<path>`.

Opt-in (marker `e2e`): `pytest tests/e2e --e2e`, or on one debug node
`qsub pbs/run_e2e.pbs`. Each test drives a subprocess exactly as a PBS script would,
on synthetic data generated by tests/e2e/synth.py, with a 2-layer hidden-32 model and
~10-20 optimizer steps. They check the wiring between stages -- argument parsing,
data loading from local paths, checkpoint layout, resume, the files each stage hands
the next -- and never model quality.

The chain: pretraining -> (contrastive, denoise, alignment) -> grouped-retrieval eval
over the contrastive encoder. Downstream stages use module-scoped fixtures, so a
failure in pretraining shows up as errors in everything that needs its checkpoint.
"""

from __future__ import annotations

import json
import math
import os
import subprocess
import sys
from pathlib import Path

import numpy as np
import pytest

from tests.e2e import synth

pytestmark = pytest.mark.e2e

REPO = Path(__file__).resolve().parents[2]
MAX_PEAKS = 64


def run_module(module: str, args: list[str], log: Path, timeout: int = 900) -> str:
    """Run `python -m module args`, tee'd to `log`; fail with the tail on non-zero exit.

    `datasets.load_dataset(<local dir>)` writes an arrow cache; it goes next to the log,
    never into the shared HF_HOME.
    """
    env = dict(os.environ)
    env.setdefault("WANDB_MODE", "disabled")
    env["HF_DATASETS_CACHE"] = str(log.parent.parent / "hf-datasets-cache")
    env["PYTHONPATH"] = str(REPO) + (os.pathsep + env["PYTHONPATH"] if env.get("PYTHONPATH") else "")
    proc = subprocess.run([sys.executable, "-m", module, *map(str, args)], cwd=REPO, env=env,
                          stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True,
                          timeout=timeout)
    log.parent.mkdir(parents=True, exist_ok=True)
    log.write_text(proc.stdout)
    if proc.returncode != 0:
        tail = "\n".join(proc.stdout.splitlines()[-60:])
        pytest.fail(f"{module} exited {proc.returncode}; log {log}\n{tail}")
    return proc.stdout


def train_log(run_dir: Path) -> list[dict]:
    """log_history of the newest checkpoint in run_dir (Trainer writes it there)."""
    ckpts = sorted(run_dir.glob("checkpoint-*"), key=lambda p: int(p.name.split("-")[1]))
    assert ckpts, f"no checkpoint under {run_dir}"
    return json.loads((ckpts[-1] / "trainer_state.json").read_text())["log_history"]


def loss_steps(history: list[dict]) -> list[int]:
    return [h["step"] for h in history if "loss" in h]


def common_training_args(out: Path, steps: int, save_steps: int) -> list[str]:
    return ["--output_dir", out, "--max_steps", steps, "--save_strategy", "steps",
            "--save_steps", save_steps, "--logging_steps", 1, "--report_to", "none",
            "--remove_unused_columns", "false", "--dataloader_num_workers", 0,
            "--seed", 0, "--warmup_steps", 0]


def assert_resumed(first: Path, resumed: Path, n_first: int, n_total: int) -> None:
    """The resumed run picks up at n_first+1 and ends at n_total, every step once.

    Identical losses for steps 1..n_first alone would not prove a resume: a run that
    silently IGNORED --resume_from_checkpoint (the bug the entry points guard against)
    retrains them deterministically. It would also save checkpoint-n_first again, so
    the resumed directory must not have one. Losses after the resume point are close to
    the uninterrupted run's but not identical (the sampler's epoch state is not
    checkpointed), so only finiteness is asserted there.
    """
    assert not (resumed / f"checkpoint-{n_first}").exists(), \
        "resumed run re-saved the resume point: it restarted from step 0"
    steps = loss_steps(train_log(resumed))
    assert steps == list(range(1, n_total + 1)), f"resumed step sequence {steps}"
    state = json.loads((resumed / f"checkpoint-{n_total}" / "trainer_state.json").read_text())
    assert state["global_step"] == n_total
    # Steps 1..n_first come from the checkpoint's own history, not from retraining them.
    original = {h["step"]: h["loss"] for h in train_log(first) if "loss" in h}
    replayed = {h["step"]: h["loss"] for h in train_log(resumed) if "loss" in h}
    for s in range(1, n_first + 1):
        assert replayed[s] == original[s]
    for s in range(n_first + 1, n_total + 1):
        assert math.isfinite(replayed[s])


# ---------------------------------------------------------------------------- fixtures

@pytest.fixture(scope="module")
def work(tmp_path_factory) -> Path:
    return tmp_path_factory.mktemp("e2e")


@pytest.fixture(scope="module")
def data(work) -> dict:
    from msdelta.models.processing_msdelta import MSDeltaProcessor
    model_dir = synth.tiny_model_dir(work / "tiny-config", MAX_PEAKS)
    return {
        "model_dir": model_dir,
        "pretraining": synth.pretraining_dataset(
            work / "pretraining-data", MSDeltaProcessor(max_peaks=MAX_PEAKS)),
        "grouped": synth.grouped_corpus(work / "grouped"),
        "denoise": synth.denoise_corpus(work / "denoise"),
    }


@pytest.fixture(scope="module")
def pretrained(work, data) -> Path:
    out = work / "pretrain"
    run_module("msdelta.pretraining.train", [
        "--config_name", data["model_dir"], "--processor_name_or_path", data["model_dir"],
        "--dataset_repo_id", "unused-local-data",
        "--preprocessed_dataset_dir", data["pretraining"],
        *common_training_args(out, 20, 10),
        "--per_device_train_batch_size", 8, "--per_device_eval_batch_size", 8,
        "--learning_rate", "3e-3", "--lr_scheduler_type", "constant",
        "--mask_ratio", 0.5, "--eval_strategy", "steps", "--eval_steps", 10,
        "--probe_execution", "off", "--bias_curve_steps", 0,
    ], work / "logs" / "pretrain.log")
    return out


GROUPED_DATA = ["--dataset_format", "grouped", "--exclude_replicate_peptides", "false",
                "--include_consensus", "false", "--max_peaks", MAX_PEAKS,
                "--preprocessing_num_workers", 0]

# The current contrastive recipe (configs/sweep-hp-single): SupCon + KL anchor, same-mass
# batches, GradCache in chunks of 4 with padding trimmed, no gradient checkpointing.
CONTRASTIVE_RECIPE = ["--loss", "supcon", "--pooling", "mean+max", "--temperature", 0.07,
                      "--kl_weight", 10, "--same_mass_batches", "true", "--mass_jitter", 1.0,
                      "--gradcache_chunk", 4, "--gradcache_trim_padding", "true",
                      "--gradient_checkpointing", "false", "--groups_per_batch", 8,
                      "--replicates", 3, "--per_device_train_batch_size", 24,
                      "--per_device_eval_batch_size", 8]


def contrastive_args(pretrained: Path, data: dict, out: Path) -> list:
    return ["--pretrained_path", pretrained / "final", "--dataset_repo", data["grouped"],
            *GROUPED_DATA, *CONTRASTIVE_RECIPE, *common_training_args(out, 10, 5),
            "--learning_rate", "1e-4", "--eval_strategy", "no", "--eval_alignment_rows", 200]


@pytest.fixture(scope="module")
def contrastive(work, data, pretrained) -> Path:
    out = work / "contrastive"
    run_module("msdelta.finetuning.contrastive.finetune_contrastive",
               contrastive_args(pretrained, data, out), work / "logs" / "contrastive.log")
    return out


# ------------------------------------------------------------------------------- tests

def test_pretraining(pretrained):
    """(a) ~20 steps on 64 spectra: loss finite and falling; checkpoint reloads."""
    import torch

    from msdelta.models.modeling_msdelta import MSDeltaForPreTraining
    history = train_log(pretrained)
    losses = [h["loss"] for h in history if "loss" in h]
    assert len(losses) == 20 and all(math.isfinite(x) for x in losses)
    assert np.mean(losses[-5:]) < np.mean(losses[:5]), losses
    assert any("eval_loss" in h and math.isfinite(h["eval_loss"]) for h in history)
    final = MSDeltaForPreTraining.from_pretrained(str(pretrained / "final"))
    ckpt = MSDeltaForPreTraining.from_pretrained(str(pretrained / "checkpoint-20"))
    assert final.config.num_hidden_layers == 2 and final.config.hidden_size == 32
    for (name, a), (_, b) in zip(final.state_dict().items(), ckpt.state_dict().items()):
        assert torch.equal(a, b), name
    assert (pretrained / "final" / "preprocessor_config.json").exists()


def test_contrastive_and_resume(work, data, pretrained, contrastive):
    """(b) current recipe for 10 steps, then resume from checkpoint-5 to step 10."""
    from msdelta.models.modeling_msdelta import MSDeltaForPreTraining
    assert (contrastive / "final" / "config.json").exists()
    MSDeltaForPreTraining.from_pretrained(str(contrastive / "final"))
    # SaveEncoderCallback: every checkpoint carries a loadable encoder.
    MSDeltaForPreTraining.from_pretrained(str(contrastive / "checkpoint-5" / "encoder"))
    losses = [h["loss"] for h in train_log(contrastive) if "loss" in h]
    assert len(losses) == 10 and all(math.isfinite(x) for x in losses)
    assert (contrastive / "separation_results.json").exists()

    resumed = work / "contrastive-resumed"
    run_module("msdelta.finetuning.contrastive.finetune_contrastive",
               contrastive_args(pretrained, data, resumed)
               + ["--resume_from_checkpoint", contrastive / "checkpoint-5"],
               work / "logs" / "contrastive-resumed.log")
    assert_resumed(contrastive, resumed, 5, 10)


def denoise_args(pretrained: Path, data: dict, out: Path) -> list:
    return ["--pretrained_path", pretrained / "final", "--dataset_repo", data["denoise"],
            "--max_peaks", MAX_PEAKS, "--preprocessing_num_workers", 0,
            "--head_hidden_size", 16, "--peak_pair_budget", MAX_PEAKS ** 2 * 16,
            *common_training_args(out, 10, 5),
            "--per_device_train_batch_size", 8, "--per_device_eval_batch_size", 8,
            "--learning_rate", "1e-3", "--eval_strategy", "steps", "--eval_steps", 5,
            "--label_names", "labels"]


def test_denoise_and_resume(work, data, pretrained):
    """(c) 10 steps + validation/test eval: AUROC/F1 finite; resume from checkpoint-5."""
    out = work / "denoise"
    run_module("msdelta.finetuning.denoise.finetune_denoise",
               denoise_args(pretrained, data, out), work / "logs" / "denoise.log")
    test = json.loads((out / "test_results.json").read_text())
    for key in ("test_auroc", "test_f1", "test_auprc"):
        assert math.isfinite(test[key]), (key, test)
    assert 0.0 <= test["test_auroc"] <= 1.0
    evals = [h for h in train_log(out) if "eval_auroc" in h]
    assert evals and all(math.isfinite(h["eval_auroc"]) and math.isfinite(h["eval_f1"])
                         for h in evals)
    assert (out / "final" / "config.json").exists()

    resumed = work / "denoise-resumed"
    run_module("msdelta.finetuning.denoise.finetune_denoise",
               denoise_args(pretrained, data, resumed)
               + ["--resume_from_checkpoint", out / "checkpoint-5"],
               work / "logs" / "denoise-resumed.log")
    assert_resumed(out, resumed, 5, 10)
    assert math.isfinite(json.loads((resumed / "test_results.json").read_text())["test_auroc"])


def test_alignment_precompute_sharded_and_train(work, data, pretrained):
    """(d) precompute_align in 2 shards (== unsharded), finetune_align 10 steps,
    final/peptide_encoder (the standard layout) loads with PeptideEncoderModel."""
    import torch
    from datasets import load_from_disk

    from msdelta.finetuning.alignment.finetune_align import peptide_encoder_dir
    from msdelta.models.peptide_encoder import PeptideEncoderModel
    common = ["--pretrained_path", pretrained / "final", "--dataset_repo", data["grouped"],
              *GROUPED_DATA, "--pooling", "mean+max", "--batch_size", 8]
    sharded, whole = work / "align-cache", work / "align-cache-whole"
    log = work / "logs"
    run_module("msdelta.finetuning.alignment.precompute_align",
               common + ["--target_cache", sharded, "--stage", "prepare"], log / "pre-prepare.log")
    for i in range(2):
        run_module("msdelta.finetuning.alignment.precompute_align",
                   common + ["--target_cache", sharded, "--stage", "shard", "--num_shards", 2,
                             "--shard_index", i, "--pad_spectra_to", MAX_PEAKS],
                   log / f"pre-shard{i}.log")
    run_module("msdelta.finetuning.alignment.precompute_align",
               common + ["--target_cache", sharded, "--stage", "merge", "--num_shards", 2],
               log / "pre-merge.log")
    run_module("msdelta.finetuning.alignment.precompute_align",
               common + ["--target_cache", whole], log / "pre-all.log")
    for split in ("train", "validation"):
        a = torch.tensor(load_from_disk(str(sharded / split))["target"])
        b = torch.tensor(load_from_disk(str(whole / split))["target"])
        assert a.shape == b.shape and a.shape[1] == 64          # mean+max of hidden 32
        assert torch.allclose(a, b, atol=1e-4), (a - b).abs().max()

    out = work / "align"
    run_module("msdelta.finetuning.alignment.finetune_align", [
        "--pretrained_path", pretrained / "final", "--dataset_repo", data["grouped"],
        *GROUPED_DATA, "--target_cache", sharded, "--pooling", "mean+max",
        "--sequence_hidden_size", 32, "--sequence_num_layers", 1, "--sequence_num_heads", 4,
        *common_training_args(out, 10, 5), "--per_device_train_batch_size", 8,
        "--per_device_eval_batch_size", 8, "--learning_rate", "1e-3",
        "--eval_strategy", "no", "--eval_alignment_rows", 100,
    ], log / "align.log")
    losses = [h["loss"] for h in train_log(out) if "loss" in h]
    assert len(losses) == 10 and all(math.isfinite(x) for x in losses)
    assert (out / "final" / "peptide_encoder" / "config.json").exists()
    assert peptide_encoder_dir(out / "final") == out / "final" / "peptide_encoder"
    peptide_encoder = PeptideEncoderModel.from_pretrained(str(out / "final" / "peptide_encoder")).eval()
    assert peptide_encoder.config.model_type == "msdelta-peptide-encoder"
    with torch.no_grad():
        emb = peptide_encoder.embed(["PEPTIDEK", "AC[57.0215]DEFGHIK"], [2, 3])
    assert emb.shape == (2, 64) and torch.isfinite(emb).all()
    assert (out / "crossmodal_results.json").exists()


def test_grouped_retrieval_eval(work, data, pretrained, contrastive):
    """(e) prepare + score on the synthetic test split: MAP@R in [0, 1] for every model."""
    prepared = work / "grouped-test-prepared"
    run_module("msdelta.eval.eval_grouped_retrieval", [
        "prepare", "--out-data", prepared, "--processor", pretrained / "final",
        "--repo", data["grouped"], "--split", "test", "--max-peaks", MAX_PEAKS,
        "--num-proc", 1, "--no-exclude-replicate"], work / "logs" / "eval-prepare.log")
    prep = json.loads((prepared / "PREPARED.json").read_text())
    assert prep["rows"] == 12 * 4                     # 12 analytes, consensus + 3 each
    models = work / "models.txt"
    models.write_text(f"pretrained {pretrained / 'final'}\n"
                      f"contrastive {contrastive / 'final'} mean+max\n"
                      "binned binned:1.0\n")
    scored = work / "grouped-scores"
    run_module("msdelta.eval.eval_grouped_retrieval", [
        "score", "--data", prepared, "--models", models, "--out-dir", scored,
        "--max-peaks", MAX_PEAKS, "--batch-size", 8], work / "logs" / "eval-score.log")
    for name in ("pretrained", "contrastive", "binned"):
        metrics = json.loads((scored / f"{name}.json").read_text())["metrics"]
        for variant in ("all", "experimental"):
            value = metrics[f"{variant}/MAP@R"]
            assert 0.0 <= value <= 1.0, (name, variant, value)


def test_psm_rerank_cli(work):
    """(f) psm_rerank score (per-run), train, score --mode global, and rerank_psm_fdr,
    on the synthetic runs of tests/test_rerank_r4.py."""
    import pandas as pd

    from tests.test_rerank_r4 import _synthetic_run, _write
    root = work / "rerank"
    rng = np.random.default_rng(0)
    for run, ds in (("runA", "HEK293"), ("runB", "HEK293"), ("runC", "HCT116")):
        rows, lab, spec, peps, owners = _synthetic_run(run, ds, 200, rng)
        _write(rows, root / "rows" / f"{run}.parquet")
        _write(lab, root / "features" / ds / f"{run}.parquet")
        d = root / "vectors" / run
        d.mkdir(parents=True)
        np.save(d / "spectrum.npy", spec.astype(np.float16))
        np.save(d / "peptide.npy", peps.astype(np.float16))
        _write({"candidate": rows["candidate"], "owner": owners,
                "null_owner": (owners + 7) % len(spec)}, d / "index.parquet")
    rows, feats, log = root / "rows", root / "features", work / "logs"
    run_module("msdelta.rescoring.psm_rerank", ["score", "--rows", rows, "--labfeat", feats,
               "--out", root / "perrun.parquet"], log / "rerank-perrun.log")
    run_module("msdelta.rescoring.psm_rerank", ["train", "--rows", rows, "--labfeat", feats,
               "--out", root / "model"], log / "rerank-train.log")
    run_module("msdelta.rescoring.psm_rerank", ["score", "--mode", "global", "--model",
               root / "model", "--rows", rows, "--labfeat", feats,
               "--out", root / "global.parquet"], log / "rerank-global.log")
    for name in ("perrun", "global"):
        out = pd.read_parquet(root / f"{name}.parquet")
        assert len(out) == 600 and out["spectrum_id"].is_unique
        assert out["q_value"].between(0, 1).all()
        # The strong synthetic signal must survive the plumbing: most accepted PSMs.
        assert (out["q_value"] <= 0.01).sum() > 100, name
    run_module("msdelta.rescoring.rerank_psm_fdr", [
        "--rows", rows, "--out", root / "fdr.json", "--models", "linear", "--labfeat", feats,
        "--vectors", root / "vectors", "--pca-k", 3, "--regime", "perrun", "--iters", 3,
        "--sets", "ms,lab", "--runs", "runA,runB,runC"], log / "rerank-fdr.log")
    methods = json.loads((root / "fdr.json").read_text())["methods"]["all"]
    assert "perrun/linear:lab+embvec" in methods
