[agent]
  interval = "10s"
  flush_interval = "10s"
  omit_hostname = true

[[inputs.execd]]
  command = ["xpu-smi", "dump", "-d", "-1", "-m", "0", "1", "2", "5"]
  signal = "none"
  restart_delay = "10s"
  data_format = "csv"
  csv_header_row_count = 1
  csv_trim_space = true
  csv_tag_columns = ["DeviceId"]
  name_override = "xpu"

[[processors.rename]]
  [[processors.rename.replace]]
    field = "GPU Utilization (%)"
    dest = "utilization_percent"

  [[processors.rename.replace]]
    field = "GPU Power (W)"
    dest = "power_watts"

  [[processors.rename.replace]]
    field = "GPU Frequency (MHz)"
    dest = "frequency_mhz"

  [[processors.rename.replace]]
    field = "GPU Memory Utilization (%)"
    dest = "memory_utilization_percent"

[[outputs.prometheus_client]]
  listen = "127.0.0.1:${MSDELTA_XPU_METRICS_PORT}"
  path = "/metrics"
  string_as_label = false
  collectors_exclude = ["gocollector", "process"]

  [outputs.prometheus_client.metric_types]
    gauge = ["xpu_*"]
